modLoader = "javafml"
loaderVersion = "[${loaderVersion},)"
issueTrackerURL = "https://github.com/MightyPirates/BedrockOres/issues"
license = "MIT"

[[mods]]
modId = "bedrockores"
version = "${version}"
displayName = "Bedrock Ores"
displayURL = "https://github.com/MightyPirates/BedrockOres"
authors = "Sangar"
description = '''
Large ore deposits embedded in the bedrock.
'''

[[dependencies.bedrockores]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.bedrockores]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[mc-publish]
modrinth = "KCMBVtfE"
curseforge = 275083
