modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/MightyPirates/BedrockOres/issues"
license = "MIT"

[[mods]]
modId = "bedrockores"
version = "${version}"
displayName = "Bedrock Ores"
displayURL = "https://github.com/MightyPirates/BedrockOres"
authors = "Sangar"
description = '''
Large ore deposits embedded in the bedrock.
'''

[[dependencies.bedrockores]]
modId = "forge"
mandatory = true
versionRange = "[44.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.bedrockores]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"
